name: Houtwerk Deploy

on:
  push:
    branches: [main]
    paths:
      - "bun/houtwerk.hering.services/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build houtwerk.hering.services
        uses: ./.github/actions/bun/build-astro
        with:
          working-directory: "bun/houtwerk.hering.services"

      - name: Upload to statichost.eu
        uses: ./.github/actions/statichost
        with:
          api-token: ${{ secrets.STATICHOST_API_KEY }}
          site-name: "houtwerk"
          # Astro outputs the built site to the 'dist' folder by default
          path: "bun/houtwerk.hering.services/dist/"

      # Add this right after your Upload to statichost.eu step
      - name: Upload Artifact for Debugging
        uses: actions/upload-artifact@v7
        with:
          name: built-site-zip
          # We need to temporarily tell our script not to delete the zip,
          # or we just upload the raw dist folder to look at the files!
          path: bun/houtwerk.hering.services/dist/
