name: Deploy `houtwerk.hering.services`

on:
  push:
    branches: [main]
    paths:
      - "bun/houtwerk.hering.services/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger StaticHost Build
        run: |
          echo "Triggering StaticHost webhook..."
          curl --fail -X POST https://builder.statichost.eu/houtwerk
          echo "Webhook triggered successfully!"
